name = "PolynomialGTM"
uuid = "d0486fca-abc3-4e94-983c-1d27790b80a4"
authors = ["Joe Carpinelli <jdcarpinelli@gmail.com>"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
julia = "1"
ModelingToolkit = "5"